
GET http://localhost:{{$dotenv BROWSERSYNCPORT}}

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students/1

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students/5
