
GET http://localhost:{{$dotenv BROWSERSYNCPORT}}

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students/1

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students/5

###

GET http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/students/a

###

POST http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/newstudent
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Wick",
    "credits": 100
}

###

PUT http://localhost:{{$dotenv BROWSERSYNCPORT}}/api/modifystudent
Content-Type: application/json

{
    "id": 1,
    "firstName": "Eka",
    "lastName": "Vekara",
    "credits": 240
}